version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:root@db:3306/hemex_ecommerce
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=${EMAIL_USER}
      - SMTP_PASS=${EMAIL_PASSWORD}
      - SMTP_FROM=${EMAIL_USER}
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
    command: npm start

  db:
    image: mysql:8.0.28
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hemex_ecommerce
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
